public class Employee {
    
    public string lName;
    public string fName;
    public string city;
    public Integer salary;
    public Integer bonus;
    public Integer exp;
    
    public Employee(){
        lName = 'Myla';
        fName = 'Satish';
        city = 'Bangaloore';
        salary = 60000;
        bonus = 6000;
        exp = 4;
        system.debug('Last Name ---'+lName);
    }


}